language: node_js
node_js:
  - "6"
  - "5"
sudo: false
script:
  - "npm run coverall"
after_script: "npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
